### ISSUE TITLE
Milestone: Refamiliarize with OV

### ISSUE THREAD

**Issue by DraxIndustries79** [WGBH-MLA/ov-deploy#47]
Review the board and refamiliarize with tickets.

```[tasklist]
### Review
- [x] Sort board tickets
- [x] Review Code
- [x] Run app locally
- [x] Run tests locally
```

**Comment by mrharpo** [comment]
🧠 ✅
