### ISSUE TITLE
🪂 Deployment

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-deploy#49]
# Deployment
Re-deploy Open Vault
```[tasklist]
### Tasks
- [x] Decide which cluster: CLAMS
- [x] Create namespaces for ov, ov-demo
- [x] Deploy tmp db
- [x] Create deployment yaml
- [x] Create backend ingress yaml
- [x] Add deployment ymls for ov-wag
- [x] Deploy backend with argo-cd
- [x] Add deployment ymls for ov-frontend
- [x] CD Frontend
- [x] Create frontend ingress
- [ ] https://github.com/WGBH-MLA/ov-deploy/issues/51
```

**Comment by DraxIndustries79** [comment]
decisions doc https://docs.google.com/document/d/1pCgZs9OKyMRpJQTo4MIXLhrQ8198paT6AoNVKyJwvfo/edit
